export default {
  selectedSemester: '1학년 1학기',
  semesters: [
    '1학년 1학기',
    '1학년 2학기',
    '2학년 1학기',
    '2학년 2학기',
    '3학년 1학기',
    '3학년 2학기',
    '4학년 1학기',
    '4학년 2학기',
  ],
  schedules: {
    월: [],
    화: [],
    수: [],
    목: [],
    금: [],
  },
  newSchedule: {
    title: '',
    startHour: '08',
    startMinute: '00',
    endHour: '08',
    endMinute: '00',
    startAmPm: '오전',
    endAmPm: '오전',
    day: '월',
  },
  scheduleColors: {},
  modalVisible: false,
  addModalVisible: false,
  selectedSchedule: {},
  selectedDay: '',
  selectedIndex: null,
};
